### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by mithro** [litex-hub/litex-renode#6]
Add info about;
 - [ ] Renode
 - [ ] LiteX
 - [ ] How to use (#2)
 - [ ] What is supported
 - [ ] What will be supported soon
 - [ ] Demos

**Comment by mithro** [comment]
@mateusz-holenko

**Comment by gojimmypi** [comment]
I tried this and was not able to get the sample to work. Apparently Vivado is required?

I found multiple `arty.py` in related repos, but not in this repo.
```
gojimmypi@ubuntu:~/workspace$ find . -type f -name arty.py
./litex/litex/boards/targets/arty.py
./litex/litex/boards/platforms/arty.py
./litex/litex-boards/litex_boards/targets/arty.py
./litex/litex-boards/litex_boards/platforms/arty.py
./litex-boards/litex_boards/targets/arty.py
./litex-boards/litex_boards/platforms/arty.py
```
The [example usage](https://github.com/litex-hub/litex-renode#usage) mentions "build your LiteX platform" (a _platform_), but nothing seems to happen when calling the `arty.py` in a `platforms` directory. Calling one of the scripts in a _targets_ directory gives an error message like this:

```
chmod -x bios.elf
 OBJCOPY  bios.bin
chmod -x bios.bin
python3 -m litex.soc.software.mkmscimg bios.bin --little
make: Leaving directory '/home/gojimmypi/workspace/litex/litex-boards/litex_boards/targets/soc_ethernetsoc_arty/software/bios'
build_top.sh: line 3: vivado: command not found
Traceback (most recent call last):
  File "arty.py", line 162, in <module>
    main()
  File "arty.py", line 158, in main
    builder.build(**vivado_build_argdict(args))
  File "/home/gojimmypi/workspace/litex/litex/soc/integration/builder.py", line 194, in build
    vns = self.soc.build(build_dir=self.gateware_dir, **kwargs)
  File "/home/gojimmypi/workspace/litex/litex/soc/integration/soc.py", line 897, in build
    return self.platform.build(self, *args, **kwargs)
  File "/home/gojimmypi/workspace/litex/litex/build/xilinx/platform.py", line 48, in build
    return self.toolchain.build(self, *args, **kwargs)
  File "/home/gojimmypi/workspace/litex/litex/build/xilinx/vivado.py", line 333, in build
    _run_script(script)
  File "/home/gojimmypi/workspace/litex/litex/build/xilinx/vivado.py", line 88, in _run_script
    raise OSError("Subprocess failed")
OSError: Subprocess failed
```
